/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
//Use control Register to move from Privileged access to Unprivileged Access
#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void level_change(void){
	__asm volatile("MRS R0,CONTROL");
	__asm volatile("ORR R0,R0,#0x01");
	__asm volatile("MSR CONTROL,R0");
}

int main(void)
{
	printf("In THREAD MODE + Privileged Access Level\n");

	level_change();

	printf("In THREAD MODE + Unprivileged Access Level\n");

	__asm volatile("MRS R0,CONTROL");

	printf("In THREAD MODE + Privileged Access Level\n");

	while(1);

}

void HardFault_Handler(void){
	__asm volatile("MRS R0,CONTROL");
	__asm volatile("AND R0,R0,#0x00");
	__asm volatile("MSR CONTROL,R0");
}
