/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	//RCC_AHB1ENR for Port D = 0x4002 3800 + x30 = 0x40023830 for CLock Supply

	uint32_t *pRcc_AHB1_EN = (uint32_t*)0x40023830;
	// Enable Port D
	*pRcc_AHB1_EN |= ( 1 << 3 );
	//Enable Port A
	*pRcc_AHB1_EN |= ( 1 << 0 );


	// GPIO mode register access to set the PD12 as Output of Port D
	//LD4 -- Green --PD12
	uint32_t *pGpio_D_Mode = (uint32_t*)0x40020C00;
	*pGpio_D_Mode |= ( 1 << 24 );
	*pGpio_D_Mode &= ~( 1 << 25);

	// GPIO mode register access to set the PA0 as Input of Port A
	uint32_t *pGpio_A_Mode = (uint32_t*)0x40020000;
	//Reset Value 0xA8000000 for port A
	//Set PA0 as Input
	*pGpio_A_Mode &= ~( 1 << 0);
	*pGpio_A_Mode &= ~( 1 << 1);

	//input data register of port A
	uint32_t *pGpio_A_Data = (uint32_t*)0x40020010;
	// output data register for PIN12 of Port D
	uint32_t *pGpio_D_Data = (uint32_t*)0x40020C14;
    /* Loop forever */

	while(1)
	{
		uint32_t pinStatus = (*pGpio_A_Data & 0x1);
		if(pinStatus)
		{
			*pGpio_D_Data |= ( 1 << 12);
		}
		else
		{
			*pGpio_D_Data &= ~( 1 << 12);
		}
	}
}
