/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
//The Aim is to provide a clock to the peripheral and enable the control register of a peripheral ADC1
#include <stdint.h>

//ADC1 register
#define ADC1_BASE_ADDR 			0x40012000UL
#define ADC_CR1_REG_OFFSET 		0x04UL
#define ADC_CR1_ADDR			(ADC1_BASE_ADDR + ADC_CR1_REG_OFFSET)

//RCC register enable for ADC1
#define RCC_BASE_ADDR			0x40023800UL
#define RCC_APB2_ENB_OFFSET		0x44UL
#define RCC_APB2ENR_REG_ADDR 	(RCC_BASE_ADDR + RCC_APB2_ENB_OFFSET)

int main(void)
{
	// 1. Enable clock to ADC1 peripheral through APB2 BUS by setting 8th bit
	uint32_t *pRccEnbADC1 = (uint32_t *) RCC_APB2ENR_REG_ADDR;
	*pRccEnbADC1 |= (1<<8);

	// 2. Access and enable ADC1 control register to set scan mode.
	uint32_t *pAdcCr1 = (uint32_t *) ADC_CR1_ADDR;
	*pAdcCr1 |= (1<<8);

    /* Loop forever */
	for(;;);
}
