/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


int main(void)
{
	//RCC_AHB1ENR for Port D = 0x4002 3800 + x30 = 0x40023830

	uint32_t *pRcc_AHB1_D = (uint32_t*)0x40023830;
	*pRcc_AHB1_D |= ( 1 << 3 );

	// GPIO mode register access to set the Pin12,13,14,15 as Output of Port D
	//LD4 -- Green --PD12
	uint32_t *pGpio_D_Mode = (uint32_t*)0x40020C00;
	*pGpio_D_Mode |= ( 1 << 24 );
	*pGpio_D_Mode &= ~( 1 << 25);

	//LD3 -- Orange -- PD13
	*pGpio_D_Mode |= ( 1 << 26 );
	*pGpio_D_Mode &= ~( 1 << 27);

	//LD5 -- Red -- PD14
	*pGpio_D_Mode |= ( 1 << 28 );
	*pGpio_D_Mode &= ~( 1 << 29);

	//LD6 -- Blue -- PD15
	*pGpio_D_Mode |= ( 1 << 30 );
	*pGpio_D_Mode &= ~( 1 << 31);

	//Writing data to GPIO D pin 12,13,14,15
	uint32_t *pGpio_D_Data = (uint32_t*)0x40020C14;

	while(1)
	{
		for(uint32_t i=0; i<10; i++)
		{

			//ON - PD12
			*pGpio_D_Data |= ( 1 << 12);
			for (uint32_t i=0;i<100000;i++);

			//OFF - PD12
			*pGpio_D_Data &= ~( 1 << 12);

			//ON - PD13
			*pGpio_D_Data |= ( 1 << 13);
			for (uint32_t i=0;i<100000;i++);

			//OFF - PD13
			*pGpio_D_Data &= ~( 1 << 13);

			//ON - PD14
			*pGpio_D_Data |= ( 1 << 14);
			for (uint32_t i=0;i<100000;i++);

			//OFF - PD14
			*pGpio_D_Data &= ~( 1 << 14);

			//ON - PD15
			*pGpio_D_Data |= ( 1 << 15);
			for (uint32_t i=0;i<100000;i++);

			//OFF - PD15
			*pGpio_D_Data &= ~( 1 << 15);
		}


		// ALL ON
		uint32_t val=15;
		for(uint32_t j=val;j>2;j--)
		{
			*pGpio_D_Data |= ( 1 << 12);
			*pGpio_D_Data |= ( 1 << 13);
			*pGpio_D_Data |= ( 1 << 14);
			*pGpio_D_Data |= ( 1 << 15);

			for (uint32_t i=0;i<(j*10000);i++);

				//ALL OFF
			*pGpio_D_Data &= ~( 1 << 12);
			*pGpio_D_Data &= ~( 1 << 13);
			*pGpio_D_Data &= ~( 1 << 14);
			*pGpio_D_Data &= ~( 1 << 15);
			for (uint32_t i=0;i<(j*10000);i++);
		}

		*pGpio_D_Data |= ( 1 << 12);
		*pGpio_D_Data |= ( 1 << 13);
		*pGpio_D_Data |= ( 1 << 14);
		*pGpio_D_Data |= ( 1 << 15);

		for (uint32_t i=0;i<800000;i++);

			//ALL OFF
		*pGpio_D_Data &= ~( 1 << 12);
		*pGpio_D_Data &= ~( 1 << 13);
		*pGpio_D_Data &= ~( 1 << 14);
		*pGpio_D_Data &= ~( 1 << 15);
		for (uint32_t i=0;i<300000;i++);


	}
}
