/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	//set The pending bit of the USART3 Interrupt in Interrupt Pending Register
    //IRQ Number = 39
	uint32_t IRQ_Num = 39;
	uint32_t *pPendReg = (uint32_t *) 0XE000E204;
	uint32_t IRQ_bit = IRQ_Num % 32;
	*pPendReg |= (1 << IRQ_bit);

	//Enable the IRQ39 = USART3 Interrupt

	uint32_t *pEnbReg = (uint32_t *) 0xE000E104;
	*pEnbReg |= (1 << IRQ_bit);

	for(;;);
}

void USART3_IRQHandler(void)
{
	printf("USART3 Interrupt\n");
}
